export type ExerciseType = 'weight_reps' | 'bodyweight_reps' | 'time' | 'distance';
export type ExerciseTier = 'daily' | 'weekly' | 'class_day';

export interface ExerciseDefinition {
  id: string;
  name: string;
  category: string;
  tier: ExerciseTier; // New explicit tier for routing/pages
  defaultSets: number;
  repRange: string;
  primaryMuscles: string[];
  type: ExerciseType;
  requiredPerWeek?: number; // Used for weekly plan tracking (5 gym days target)
  isAssisted?: boolean;
  defaultWeightKg?: number;
  defaultTimeSeconds?: number;
  notes?: string;
}

export interface WeeklyCategoryGoal {
  id: string;
  name: string;
  targetCount: number; // Tailored for your 5-day split
  unitLabel: string;
}

// -----------------------------------------------------------------------------
// WEEKLY CATEGORY GOALS (Adjusted for 5 Gym Days)
// -----------------------------------------------------------------------------
export const WEEKLY_CATEGORIES: WeeklyCategoryGoal[] = [
  { id: 'lower_body', name: 'Lower Body Strength', targetCount: 6, unitLabel: 'exercises' },
  { id: 'upper_push', name: 'Upper Push', targetCount: 5, unitLabel: 'exercises' },
  { id: 'upper_pull', name: 'Upper Pull', targetCount: 7, unitLabel: 'exercises' },
  { id: 'full_body', name: 'Full Body Strength', targetCount: 6, unitLabel: 'exercises' },
  { id: 'core_a', name: 'Core A', targetCount: 5, unitLabel: 'exercises' },
  { id: 'core_b', name: 'Core B', targetCount: 5, unitLabel: 'exercises' },
  { id: 'grip', name: 'Grip Training', targetCount: 2, unitLabel: 'sessions' },
];

export const EXERCISE_DATABASE: ExerciseDefinition[] = [

// ===========================================================================
  // PAGE 1: DAILY EXERCISES (Posture, Grip & Movement Skill Options)
  // ===========================================================================
  
  // --- 1. CORE POSTURE (Required Daily) ---
  {
    id: 'day_chin_tuck',
    name: 'Chin Tucks',
    category: 'posture',
    tier: 'daily',
    defaultSets: 2,
    repRange: '15 reps',
    primaryMuscles: ['Neck', 'Posture'],
    type: 'bodyweight_reps',
  },
  {
    id: 'day_wall_angels',
    name: 'Wall Angels',
    category: 'posture',
    tier: 'daily',
    defaultSets: 2,
    repRange: '10-12 reps',
    primaryMuscles: ['Upper Back', 'Shoulders'],
    type: 'bodyweight_reps',
  },

  // --- 2. GRIP OPTIONS (Choose 1 or More) ---
  {
    id: 'day_farmer_carry',
    name: 'Farmer Carry',
    category: 'grip',
    tier: 'daily',
    defaultSets: 3,
    repRange: '30s hold',
    primaryMuscles: ['Grip', 'Core', 'Traps'],
    type: 'time',
    defaultTimeSeconds: 30,
  },
  {
    id: 'day_plate_hold',
    name: 'Plate Hold',
    category: 'grip',
    tier: 'daily',
    defaultSets: 2,
    repRange: '30s hold',
    primaryMuscles: ['Grip Strength'],
    type: 'time',
    defaultTimeSeconds: 30,
  },
  {
    id: 'day_dead_hang',
    name: 'Assisted Dead Hang',
    category: 'grip',
    tier: 'daily',
    defaultSets: 2,
    repRange: '10-20s hold',
    primaryMuscles: ['Grip', 'Shoulders'],
    type: 'time',
    defaultTimeSeconds: 10,
  },

  // --- 3. MOVEMENT SKILL OPTIONS (Choose 1 or More) ---
  {
    id: 'day_plank_prog',
    name: 'Plank Progression',
    category: 'movement_skill',
    tier: 'daily',
    defaultSets: 3,
    repRange: '30-60s hold',
    primaryMuscles: ['Core Stability'],
    type: 'time',
    defaultTimeSeconds: 30,
  },
  {
    id: 'day_pushup_prog',
    name: 'Push-up Progression',
    category: 'movement_skill',
    tier: 'daily',
    defaultSets: 3,
    repRange: '8-12 reps',
    primaryMuscles: ['Chest', 'Core'],
    type: 'bodyweight_reps',
  },
  {
    id: 'day_pullup_tech',
    name: 'Pull-up Technique Practice',
    category: 'movement_skill',
    tier: 'daily',
    defaultSets: 3,
    repRange: '5 reps',
    primaryMuscles: ['Back', 'Biceps'],
    type: 'bodyweight_reps',
  },
  {
    id: 'day_deep_squat',
    name: 'Deep Squat Hold',
    category: 'movement_skill',
    tier: 'daily',
    defaultSets: 2,
    repRange: '45s hold',
    primaryMuscles: ['Hips', 'Ankles'],
    type: 'time',
    defaultTimeSeconds: 45,
  },
  {
    id: 'day_single_leg_bal',
    name: 'Single-Leg Balance Practice',
    category: 'movement_skill',
    tier: 'daily',
    defaultSets: 2,
    repRange: '30s / side',
    primaryMuscles: ['Ankle Stabilizers', 'Glutes'],
    type: 'time',
    defaultTimeSeconds: 30,
  },
  {
    id: 'day_floor_stand',
    name: 'Floor Stand Practice',
    category: 'movement_skill',
    tier: 'daily',
    defaultSets: 2,
    repRange: '5-10 reps',
    primaryMuscles: ['Full Body', 'Mobility'],
    type: 'bodyweight_reps',
  },

  // ===========================================================================
  // PAGE 2: WEEKLY GYM PLAN (5 Gym Days Split)
  // ===========================================================================
  // LOWER BODY STRENGTH
  {
    id: 'lb_squat',
    name: 'Barbell Back Squat',
    category: 'lower_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Quads', 'Glutes'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 15,
  },
  {
    id: 'lb_hip_thrust',
    name: 'Barbell Hip Thrust',
    category: 'lower_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Glutes', 'Hamstrings'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 20,
  },
  {
    id: 'lb_rdl',
    name: 'Romanian Deadlift (RDL)',
    category: 'lower_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Hamstrings', 'Glutes'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 7.5,
  },
  {
    id: 'lb_leg_curl',
    name: 'Leg Curl',
    category: 'lower_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Hamstrings'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 15,
  },
  {
    id: 'lb_adductor',
    name: 'Hip Adductor',
    category: 'lower_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Inner Thighs'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 7.5,
  },
  {
    id: 'lb_calf_raise',
    name: 'Standing Calf Raise',
    category: 'lower_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Calves'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 7.5,
  },

  // UPPER PUSH
  {
    id: 'up_db_bench',
    name: 'Incline Bench Press',
    category: 'upper_push',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Chest', 'Triceps'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 15,
  },
  {
    id: 'up_db_shoulder',
    name: 'Dumbbell Shoulder Press',
    category: 'upper_push',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Shoulders', 'Triceps'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 5,
  },
  {
    id: 'up_lat_raise',
    name: 'Dumbbell Lateral Raise',
    category: 'upper_push',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Side Delts'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 2.5,
  },
  {
    id: 'up_tricep_pushdown',
    name: 'Cable Triceps Pushdown',
    category: 'upper_push',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Triceps'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 10,
  },
  {
    id: 'up_incline_pushup',
    name: 'Incline Push-ups',
    category: 'upper_push',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Chest', 'Core'],
    type: 'bodyweight_reps',
    requiredPerWeek: 1,
  },

  // UPPER PULL
  {
    id: 'upl_assisted_pullup',
    name: 'Assisted Pull-up',
    category: 'upper_pull',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Lats', 'Biceps', 'Grip'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    isAssisted: true,
    defaultWeightKg: 92,
  },
  {
    id: 'upl_assisted_chinup',
    name: 'Assisted Chin-up',
    category: 'upper_pull',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Lats', 'Biceps'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    isAssisted: true,
    defaultWeightKg: 92,
  },
  {
    id: 'upl_lat_pulldown',
    name: 'Lat Pulldown',
    category: 'upper_pull',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Upper Back', 'Lats'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 15,
  },
  {
    id: 'upl_seated_row',
    name: 'Seated Row',
    category: 'upper_pull',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Mid Back', 'Rhomboids'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 20,
  },
  {
    id: 'upl_rear_delt',
    name: 'Rear Delt Fly',
    category: 'upper_pull',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Rear Delts'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 10,
  },
  {
    id: 'upl_face_pull',
    name: 'Cable Face Pull',
    category: 'upper_pull',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Posture', 'Rear Delts'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 15,
  },
  {
    id: 'upl_hammer_curl',
    name: 'Dumbbell Hammer Curl',
    category: 'upper_pull',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Biceps', 'Forearms'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 5,
  },

  // FULL BODY
  {
    id: 'fb_goblet_squat',
    name: 'Goblet Squat',
    category: 'full_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Quads', 'Core'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 7.5,
  },
  {
    id: 'fb_kb_swing',
    name: 'Kettlebell Swing',
    category: 'full_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '10-15',
    primaryMuscles: ['Glutes', 'Posterior Chain'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 15,
  },
  {
    id: 'fb_farmer_carry',
    name: 'Farmer Carry',
    category: 'full_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '30-50m',
    primaryMuscles: ['Grip', 'Core', 'Traps'],
    type: 'distance',
    requiredPerWeek: 1,
    defaultWeightKg: 12.5,
  },
  {
    id: 'fb_suitcase_carry',
    name: 'Suitcase Carry',
    category: 'full_body',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '30m / side',
    primaryMuscles: ['Obliques', 'Grip'],
    type: 'distance',
    requiredPerWeek: 1,
    defaultWeightKg: 12.5,
  },

  // CORE A & B
  {
    id: 'ca_cable_crunch',
    name: 'Cable Crunch',
    category: 'core_a',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Abs'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 30,
  },
  {
    id: 'ca_leg_raise',
    name: 'Lying Leg Raise',
    category: 'core_a',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12',
    primaryMuscles: ['Lower Abs'],
    type: 'bodyweight_reps',
    requiredPerWeek: 1,
  },
  {
    id: 'ca_heel_taps',
    name: 'Heel Taps',
    category: 'core_a',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '20',
    primaryMuscles: ['Obliques'],
    type: 'bodyweight_reps',
    requiredPerWeek: 1,
  },
  {
    id: 'ca_bird_dog',
    name: 'Bird Dog',
    category: 'core_a',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-12 / side',
    primaryMuscles: ['Lower Back', 'Core'],
    type: 'bodyweight_reps',
    requiredPerWeek: 1,
  },
  {
    id: 'ca_plank',
    name: 'Plank Practice',
    category: 'core_a',
    tier: 'weekly',
    defaultSets: 3,
    repRange: 'Max hold',
    primaryMuscles: ['Core Stability'],
    type: 'time',
    requiredPerWeek: 1,
    defaultTimeSeconds: 30,
  },
  {
    id: 'cb_side_leg_lowers',
    name: 'Slow Side-to-Side Leg Lowers',
    category: 'core_b',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '8-10',
    primaryMuscles: ['Obliques', 'Abs'],
    type: 'bodyweight_reps',
    requiredPerWeek: 1,
  },
  {
    id: 'cb_bicycle_crunch',
    name: 'Bicycle Crunch',
    category: 'core_b',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '12-15',
    primaryMuscles: ['Obliques'],
    type: 'bodyweight_reps',
    requiredPerWeek: 1,
  },
  {
    id: 'cb_russian_twist',
    name: 'Russian Twist',
    category: 'core_b',
    tier: 'weekly',
    defaultSets: 3,
    repRange: '12-15',
    primaryMuscles: ['Rotational Core'],
    type: 'weight_reps',
    requiredPerWeek: 1,
    defaultWeightKg: 5,
  },

  // GRIP
  {
    id: 'hab_dead_hang',
    name: 'Assisted Dead Hang',
    category: 'grip',
    tier: 'weekly',
    defaultSets: 2,
    repRange: 'Max hold',
    primaryMuscles: ['Grip', 'Shoulders'],
    type: 'time',
    requiredPerWeek: 1,
    defaultTimeSeconds: 10,
  },
  {
    id: 'hab_plate_hold',
    name: 'Plate Hold',
    category: 'grip',
    tier: 'weekly',
    defaultSets: 2,
    repRange: '30-45s hold',
    primaryMuscles: ['Grip Strength'],
    type: 'time',
    requiredPerWeek: 1,
    defaultTimeSeconds: 30,
  },

  // ===========================================================================
  // PAGE 3: HIGH INTENSITY CLASS DAYS (Variable Frequency / On-Demand)
  // ===========================================================================
  {
    id: 'mob_deep_squat',
    name: 'Deep Squat Hold',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '60s hold',
    primaryMuscles: ['Hips', 'Ankles', 'Pelvic Floor'],
    type: 'time',
    defaultTimeSeconds: 30,
  },
  {
    id: 'mob_ankle_rocks',
    name: 'Ankle Rocks',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '10-12 / side',
    primaryMuscles: ['Ankles', 'Calves'],
    type: 'bodyweight_reps',
  },
  {
    id: 'mob_butterfly',
    name: 'Butterfly Stretch',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '60s hold',
    primaryMuscles: ['Adductors', 'Hips'],
    type: 'time',
    defaultTimeSeconds: 60,
  },
  {
    id: 'mob_9090',
    name: '90/90 Hip Stretch',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '60s / side',
    primaryMuscles: ['Hip Rotators'],
    type: 'time',
    defaultTimeSeconds: 60,
  },
  {
    id: 'mob_hip_flexor',
    name: 'Hip Flexor Stretch',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '45s / side',
    primaryMuscles: ['Hip Flexors', 'Psoas'],
    type: 'time',
    defaultTimeSeconds: 45,
  },
  {
    id: 'mob_cat_cow',
    name: 'Cat-Cow',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '10-12 reps',
    primaryMuscles: ['Spine'],
    type: 'bodyweight_reps',
  },
  {
    id: 'mob_thread_needle',
    name: 'Thread the Needle',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '10 / side',
    primaryMuscles: ['Thoracic Spine'],
    type: 'bodyweight_reps',
  },
  {
    id: 'mob_doorway_chest',
    name: 'Doorway Chest Stretch',
    category: 'mobility',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '45s hold',
    primaryMuscles: ['Chest', 'Shoulders'],
    type: 'time',
    defaultTimeSeconds: 45,
  },
  {
    id: 'bal_single_leg_stand',
    name: 'Single-Leg Stand',
    category: 'balance',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '45s / side',
    primaryMuscles: ['Ankle Stabilizers', 'Glute Medius'],
    type: 'time',
    defaultTimeSeconds: 45,
  },
  {
    id: 'bal_sl_rdl_bw',
    name: 'Bodyweight Single-Leg RDL',
    category: 'balance',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '8-10 / side',
    primaryMuscles: ['Hamstrings', 'Glute Stabilizers'],
    type: 'bodyweight_reps',
  },
  {
    id: 'bal_heel_toe_walk',
    name: 'Heel-to-Toe Walk',
    category: 'balance',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '20 steps',
    primaryMuscles: ['Foot Proprioception'],
    type: 'bodyweight_reps',
  },
  {
    id: 'bal_assisted_squat_hold',
    name: 'Assisted Deep Squat Hold',
    category: 'balance',
    tier: 'class_day',
    defaultSets: 2,
    repRange: '45-60s hold',
    primaryMuscles: ['Joint Stability', 'Ankles'],
    type: 'time',
    defaultTimeSeconds: 45,
  },
];